# Conditional Filtering

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Dataset/Car_Sales.csv')
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [9]:
# Find car details whose model year is 2017.
# filter_car = df['year'] == 2017
# df[filter_car]

# select * from cars where year = 2017;
df[df['year'] == 2017][['name', 'year', 'selling_price']]

                                 name  year  selling_price
3              Datsun RediGO T Option  2017         250000
9            Maruti Celerio Green VXI  2017         365000
16             Datsun RediGO T Option  2017         250000
22           Maruti Celerio Green VXI  2017         365000
54    Maruti Swift Dzire VDI Optional  2017         725000
...                               ...   ...            ...
4264           Hyundai i20 1.4 Sportz  2017         680000
4273           Maruti Ertiga SHVS VDI  2017         890000
4309                 Datsun GO Plus T  2017         350000
4311          Toyota Camry Hybrid 2.5  2017        1900000
4315               Maruti Celerio ZXI  2017         415000

[466 rows x 3 columns]

In [14]:
# Find car details whose price is in range of 300000 to 600000.
car_price = df[(df['selling_price'] >= 300000) & (df['selling_price'] <= 600000)]
car_price

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner
15,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4322,Hyundai Verna 1.6 SX CRDi (O),2013,500000,120000,Diesel,Individual,Manual,First Owner
4331,Ford EcoSport 1.5 TDCi Titanium BSIV,2015,530000,175000,Diesel,Individual,Manual,Third Owner
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,600000,170000,Diesel,Individual,Manual,First Owner
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner

In [12]:
car_price_between = df[df['selling_price'].between(300000, 600000)]
car_price_between

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner
15,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4322,Hyundai Verna 1.6 SX CRDi (O),2013,500000,120000,Diesel,Individual,Manual,First Owner
4331,Ford EcoSport 1.5 TDCi Titanium BSIV,2015,530000,175000,Diesel,Individual,Manual,Third Owner
4334,Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV,2012,600000,170000,Diesel,Individual,Manual,First Owner
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner

In [15]:
# to find unique values
df['fuel'].unique()

array(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [16]:
# to find number of unique values in a column
df['fuel'].nunique()

5

In [17]:
# Find cars whose emmission fuel type is Petrol or CNG.
car_fuel = df[(df['fuel'] == 'Petrol') | (df['fuel'] == 'CNG')]
car_fuel

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4326,Honda City 1.5 GXI,2005,65000,150000,Petrol,Individual,Manual,Third Owner
4327,Tata Nano XM,2015,190000,60000,Petrol,Individual,Manual,Second Owner
4329,Tata Manza Aura Safire BS IV,2010,160000,60000,Petrol,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [26]:
car_fuel_in = df[df['fuel'].isin(['Petrol', 'CNG'])]
# unique_fuel = car_fuel_in['fuel'].unique()
# unique_fuel
car_fuel_in

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
...,...,...,...,...,...,...,...,...
4326,Honda City 1.5 GXI,2005,65000,150000,Petrol,Individual,Manual,Third Owner
4327,Tata Nano XM,2015,190000,60000,Petrol,Individual,Manual,Second Owner
4329,Tata Manza Aura Safire BS IV,2010,160000,60000,Petrol,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [33]:
'''
Find car details which is transmission mode is Automatic, Fuel type is Petrol/Diesel and
which is driven for around 20000 to 35000 range.
'''
car_details = df[(df['transmission'] == 'Automatic') & 
                ((df['fuel'] == 'Petrol') | (df['fuel'] == 'Diesel')) &
                ((df['km_driven'] >= 20000) & (df['km_driven']<= 35000))][['name', 'year']]
car_details

                                                name  year
12                   Toyota Corolla Altis 1.8 VL CVT  2018
25                   Toyota Corolla Altis 1.8 VL CVT  2018
29                        Jaguar XF 2.2 Litre Luxury  2014
36    Mercedes-Benz New C-Class C 220 CDI Avantgarde  2012
94                      Audi A6 2.0 TDI Premium Plus  2014
...                                              ...   ...
4254                    Hyundai Verna CRDi 1.6 AT EX  2018
4274                    Hyundai Verna CRDi 1.6 AT EX  2018
4302                              BMW 7 Series 730Ld  2006
4304              Audi Q5 3.0 TDI Quattro Technology  2018
4311                         Toyota Camry Hybrid 2.5  2017

[89 rows x 2 columns]

In [ ]:
'''
Data Types
============
- Int, Str, Bool, None, Complex, Float, DateTime

Types of Data
==============
- Numeric
    - Discrete -> Whole Numbers (Positive / Negative) -> ID Columns

    - Continuous -> Whole Numbers / Decimal Numbers (Positive / Negative)
        -> Salary, Temperature, Sales

- Categorical
    - Nominal -> Category which cannot be compared
        -> Gender, Caste, Colors, ...

    - Ordinal -> Category which can be compared
        -> Grades, Disease Stages, ...
'''

In [2]:
df = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [3]:
df['Department'].unique()

array(['Production       ', 'IT/IS', 'Software Engineering',
       'Admin Offices', 'Sales', 'Executive Office'], dtype=object)

In [8]:
dep_satisfaction = df[(df['Department'] == 'Production       ') & (df['EmpSatisfaction'] < 3)]
dep_satisfaction

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
73,"Corleone, Michael",10282,0,2,1,1,5,2,0,68051,...,Janet King,2.0,CareerBuilder,Needs Improvement,4.13,2,0,1/14/2019,3,3
88,"Desimone, Carl",10310,1,1,1,1,5,1,0,53189,...,Amy Dunn,11.0,Indeed,PIP,1.12,2,0,1/31/2019,4,9
102,"Erilus, Angela",10299,0,3,0,1,5,1,0,56847,...,Michael Albert,22.0,Indeed,PIP,3.00,1,0,2/25/2019,2,5
156,"Immediato, Walter",10289,1,1,1,5,5,2,0,83082,...,Janet King,2.0,Indeed,Needs Improvement,2.34,2,0,4/12/2012,3,4
207,"Miller, Ned",10298,0,0,1,5,5,1,0,55800,...,Brannon Miller,12.0,LinkedIn,PIP,3.00,2,0,1/14/2013,6,6
224,"O'hare, Lynn",10303,0,0,0,4,5,1,0,52674,...,Kissy Sullivan,20.0,LinkedIn,PIP,2.33,2,0,3/9/2018,6,3
282,"Sparks, Taylor",10302,1,1,0,1,5,1,0,64021,...,Brannon Miller,12.0,Indeed,PIP,2.40,2,1,2/25/2019,6,20
326,"Ybarra, Catherine",10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12.0,Google Search,PIP,3.20,2,0,9/2/2015,5,4