# Data Cleaning

In [ ]:
'''
1. Handle Missing / Null Values
    a. Fill Null Values
        -> .fillna()
        - Continuous Data
        i. Mean
        ii. Median

        -> Skewness -> .skew()
            -> 0 - 0.5 -> Fill Mean Value
            -> < 0 (Negative Skewness) or > 0.5 (Positive Skewness) -> Fill Median Value

        -> Calculate Mean and Median value of a column.
            -> If both mean and median value are equal or almost equal then fill mean value.
            -> If both mean and median value are not equal has vast difference in values then fill median value.
        
        - Discrete / Categorical
        iii. Mode

        - Continuous / Discrete / Categorical
        iv. Custom Record

        
    b. Drop Null Values
        -> .dropna()
    
2. Remove unwanted data
    -> Remove Whitespace
        -> .strip(), .lstrip(), .rstrip()

    -> Remove Regular Expressions (regex) if needed / Remove unwanted texts
        -> .replace()

3. Change Datatypes
    .astype()

4. Handle Duplicate Records
    -> Find duplicate records
        -> .duplicated()

    -> To remove duplicate records
        -> .drop_duplicates()
'''

In [1]:
import pandas as pd

In [15]:
df = pd.read_csv('Dataset/Employees.csv')
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 107 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     107 non-null    int64
 1   FIRST_NAME      107 non-null    object
 2   LAST_NAME       107 non-null    object
 3   EMAIL           107 non-null    object
 4   PHONE_NUMBER    107 non-null    object
 5   HIRE_DATE       107 non-null    object
 6   JOB_ID          107 non-null    object
 7   SALARY          107 non-null    int64
 8   COMMISSION_PCT  107 non-null    float64
 9   MANAGER_ID      107 non-null    float64
 10  DEPARTMENT_ID   107 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 10.0+ KB

In [14]:
# check null values
# df.isnull().sum().sum()| # Shows total null values in dataset
df.isnull().sum() # shows column name and total null values in column

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        1
DEPARTMENT_ID     1
dtype: int64

## Drop Null Values

In [5]:
'''
- dropna(axis=0/1, how='any'/'all', inplace=True/False)

- axis -> 0 -> Row / 1 -> Column

- how
    - any -> data should have any one null value
    - all -> data must have all null value
    
- inplace
    - True -> Permanent change to data
    - False -> Temporary change to data
'''

"\n- dropna(axis=0/1, how='any'/'all', inplace=True/False)\n\n- axis -> 0 -> Row / 1 -> Column\n\n- how\n    - any -> data should have any one null value\n    - all -> data must have all null value\n\n- inplace\n    - True -> Permanent change to data\n    - False -> Temporary change to data\n"

In [29]:
# df = df.dropna()
# inplace = True / False (default)
# df.dropna(inplace=True)

In [48]:
# df.dropna(axis=0, how='all', inplace=False)

In [49]:
# Drop any column
# df.drop(columns=['COMMISSION_PCT', 'PHONE_NUMBER'], inplace=False)

In [55]:
# Drop Rows
# df.drop(index=[0, 1, 2], inplace=False)

## Handle Duplicate Records

### Find duplicate records

In [56]:
duplicate_data = df[df.duplicated(subset=['EMPLOYEE_ID'], keep=False)]
duplicate_data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,0.0,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,0.0,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,0.0,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.0,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,0.0,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,0.0,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,0.0,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,0.0,205.0,110.0

### Remove duplicate records

In [57]:
df.drop_duplicates(subset='EMPLOYEE_ID', keep='last', inplace=True)

## Fill Null Values

In [48]:
df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     0
dtype: int64

### Fill commission value

In [10]:
commission_mean = round(df['COMMISSION_PCT'].mean(), 2)
commission_median = df['COMMISSION_PCT'].median()
commission_skew = df['COMMISSION_PCT'].skew()

In [33]:
print(commission_mean)
print(commission_median)
print(commission_skew)

df = pd.read_csv('Dataset/Employees.csv')
# df

0.22
0.2
0.09661736135041571

In [18]:
# df['COMMISSION_PCT'].fillna(commission_mean, inplace=True)

In [23]:
# df.fillna({'COMMISSION_PCT':commission_mean}, inplace=True)

In [34]:
# df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(commission_mean)

In [38]:
# df.fillna({'COMMISSION_PCT':0}, inplace=True)

In [39]:
df['COMMISSION_PCT'].unique()

array([0.  , 0.4 , 0.3 , 0.2 , 0.25, 0.15, 0.35, 0.1 ])

### Fill Manager and Department Values

In [51]:
mgr_mode = df['MANAGER_ID'].mode()[0]
dep_mode = df['DEPARTMENT_ID'].mode()[0]

In [52]:
print('Manager Mode:',mgr_mode)
print('\nDepartment Mode:',dep_mode)

Manager Mode: 100.0

Department Mode: 50.0

In [47]:
df.fillna({'MANAGER_ID':mgr_mode}, inplace=True)
df.fillna({'DEPARTMENT_ID':dep_mode}, inplace=True)

In [61]:
df.to_csv('cleaned_employee.csv', index=False)
df.to_excel('cleaned_employee.xlsx', index=False)
df.to_json('cleaned_employee.json', indent=4)

# HR Dataset Refresh

In [68]:
hr = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
hr.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [69]:
# hr.info()

In [70]:
# hr.isnull().sum()

### Fill Manager Null Value

In [71]:
hr.fillna({'ManagerID': 39}, inplace=True)

### Find duplicate record

In [72]:
duplicate_emp = hr[hr.duplicated(subset='EmpID')]
# duplicate_emp

#### validate duplicate records

In [73]:
# emp_id = int(input('Enter employee id: '))
# duplicates = hr[hr['EmpID'] == emp_id]
# duplicates

### Remove duplicate record

In [74]:
hr = hr.drop_duplicates(subset='EmpID')

## Remove unwanted values

### Remove whitespaces

In [75]:
# strip(), lstrip(), rstrip()

In [76]:
hr['Department'] = hr['Department'].str.strip()

In [77]:
hr['Department'].unique()

array(['Production', 'IT/IS', 'Software Engineering', 'Admin Offices',
       'Sales', 'Executive Office'], dtype=object)

In [78]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
Index: 311 entries, 0 to 329
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    object
 16  Gender                      311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    object
 22  DateofTermination           104 non-null    object
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   311 non-null    float64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    object
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 89.9+ KB

### Extract specific data types columns

In [79]:
# select_dtypes()
object_columns = hr.select_dtypes(['object'])
object_columns = object_columns.drop(columns=['DOB', 'DateofHire', 'DateofTermination', 'LastPerformanceReview_Date'])
object_columns

,Employee_Name,Position,State,Gender,MaritalDesc,CitizenDesc,HispanicLatino,RaceDesc,TermReason,EmploymentStatus,Department,ManagerName,RecruitmentSource,PerformanceScore
0,"Adinolfi, Wilson K",Production Technician I,MA,M,Single,US Citizen,No,White,N/A-StillEmployed,Active,Production,Michael Albert,LinkedIn,Exceeds
1,"Ait Sidi, Karthikeyan",Sr. DBA,MA,M,Married,US Citizen,No,White,career change,Voluntarily Terminated,IT/IS,Simon Roup,Indeed,Fully Meets
2,"Akinkuolie, Sarah",Production Technician II,MA,F,Married,US Citizen,No,White,hours,Voluntarily Terminated,Production,Kissy Sullivan,LinkedIn,Fully Meets
3,"Alagbe,Trina",Production Technician I,MA,F,Married,US Citizen,No,White,N/A-StillEmployed,Active,Production,Elijiah Gray,Indeed,Fully Meets
4,"Anderson, Carol",Production Technician I,MA,F,Divorced,US Citizen,No,White,return to school,Voluntarily Terminated,Production,Webster Butler,Google Search,Fully Meets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,"Woodson, Jason",Production Technician II,MA,M,Single,US Citizen,No,White,N/A-StillEmployed,Active,Production,Kissy Sullivan,LinkedIn,Fully Meets
326,"Ybarra, Catherine",Production Technician I,MA,F,Single,US Citizen,No,Asian,Another position,Voluntarily Terminated,Production,Brannon Miller,Google Search,PIP
327,"Zamora, Jennifer",CIO,MA,F,Single,US Citizen,No,White,N/A-StillEmployed,Active,IT/IS,Janet King,Employee Referral,Exceeds
328,"Zhou, Julia",Data Analyst,MA,F,Single,US Citizen,No,White,N/A-StillEmployed,Active,IT/IS,Simon Roup,Employee Referral,Fully Meets
329,"Zima, Colleen",Production Technician I,MA,F,Widowed,US Citizen,No,Asian,N/A-StillEmployed,Active,Production,David Stanley,LinkedIn,Fully Meets

In [80]:
# hr['Employee_Name'].unique()

In [81]:
object_columns.columns

Index(['Employee_Name', 'Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'TermReason',
       'EmploymentStatus', 'Department', 'ManagerName', 'RecruitmentSource',
       'PerformanceScore'],
      dtype='object')

### Checking whitespaces

In [82]:
columns = ['Employee_Name', 'Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'TermReason',
       'EmploymentStatus', 'Department', 'ManagerName', 'RecruitmentSource',
       'PerformanceScore']

# for col in columns:
#     print(col)
#     print('-'*20)
#     unique_values = hr[col].unique()
#     print(unique_values)
#     print('\n')

### Creating function for removing whitespaces

In [83]:
def removeWhitespace(dataframe, columns):
    for col in columns:
        dataframe[col] = dataframe[col].str.strip()
    print('Whitespaces removed.')

In [84]:
removeWhitespace(hr, columns)

Whitespaces removed.

## Replace

In [85]:
'''
# Removing unwanted text, regular expressions (regex)
syntax
---------
-> for text/characters/digits
    - str.replace(find, replace_value)

-> for special characters
    - str.replace(find, replace_value, regex=False/True(default))
'''

'\n# Removing unwanted text, regular expressions (regex)\nsyntax\n---------\n-> for text/characters/digits\n    - str.replace(find, replace_value)\n\n-> for special characters\n    - str.replace(find, replace_value, regex=False/True(default))\n'

In [86]:
hr['HispanicLatino'].unique()

array(['No', 'Yes', 'no', 'yes'], dtype=object)

In [87]:
hr['HispanicLatino'] = hr['HispanicLatino'].str.replace('yes', 'Yes')

In [88]:
hr['HispanicLatino'] = hr['HispanicLatino'].str.capitalize()

In [89]:
hr['Employee_Name'] = hr['Employee_Name'].str.replace(',', '', regex=False)

## Datatype Conversion

In [90]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
Index: 311 entries, 0 to 329
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    object
 16  Gender                      311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    object
 22  DateofTermination           104 non-null    object
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   311 non-null    float64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    object
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 89.9+ KB

In [91]:
### astype(datatype)
hr['ManagerID'] = hr['ManagerID'].astype(int)

In [92]:
'''
- pandas function -> pd.to_datetime(column, format/dayfirst)
- After conversion -> YYYY-MM-DD

Format
---------
- '%d.%m.%y'
- '%d-%m-%y'
- mixed

dayfirst = True/False (default)
'''

"\n- pandas function -> pd.to_datetime(column, format/dayfirst)\n- After conversion -> YYYY-MM-DD\n\nFormat\n---------\n- '%d.%m.%y'\n- '%d-%m-%y'\n- mixed\n\ndayfirst = True/False (default)\n"

In [93]:
# date_columns=['DOB', 'DateofHire', 'DateofTermination', 'LastPerformanceReview_Date']

In [94]:
hr['DOB'] = pd.to_datetime(hr['DOB'])

#### Function to convert datetime

In [95]:
def dateConverter(dataframe, *args):
    for col in args:
        hr[col] = pd.to_datetime(hr[col], format='mixed')
    print('Datetime converted.')

In [96]:
dateConverter(hr, 'DOB', 'DateofHire', 'DateofTermination', 'LastPerformanceReview_Date')

Datetime converted.

In [97]:
# hr['ManagerID'] = hr['ManagerID'].astype(int)

In [98]:
hr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22,LinkedIn,Exceeds,4.60,5,0,2019-01-17,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4,Indeed,Fully Meets,4.96,3,6,2016-02-24,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20,LinkedIn,Fully Meets,3.02,3,0,2012-05-15,0,3
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16,Indeed,Fully Meets,4.84,5,0,2019-01-03,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39,Google Search,Fully Meets,5.00,4,0,2016-02-01,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Woodson Jason,10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20,LinkedIn,Fully Meets,4.07,4,0,2019-02-28,0,13
326,Ybarra Catherine,10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12,Google Search,PIP,3.20,2,0,2015-09-02,5,4
327,Zamora Jennifer,10010,0,0,0,1,3,4,0,220450,...,Janet King,2,Employee Referral,Exceeds,4.60,5,6,2019-02-21,0,16
328,Zhou Julia,10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4,Employee Referral,Fully Meets,5.00,3,5,2019-02-01,0,11
329,Zima Colleen,10271,0,4,0,1,5,3,0,45046,...,David Stanley,14,LinkedIn,Fully Meets,4.50,5,0,2019-01-30,0,2

In [99]:
hr.to_csv('cleaned_hr.csv', index=False)
hr.to_excel('cleaned_hr.xlsx', index=False)

In [103]:
# xl = pd.read_excel('cleaned_hr.xlsx')
# xl.info()

In [104]:
# csv = pd.read_csv('cleaned_hr.csv')
# csv.info()

In [102]:
csv

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22,LinkedIn,Exceeds,4.60,5,0,2019-01-17,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4,Indeed,Fully Meets,4.96,3,6,2016-02-24,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20,LinkedIn,Fully Meets,3.02,3,0,2012-05-15,0,3
3,AlagbeTrina,10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16,Indeed,Fully Meets,4.84,5,0,2019-01-03,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39,Google Search,Fully Meets,5.00,4,0,2016-02-01,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,Woodson Jason,10135,0,0,1,1,5,3,0,65893,...,Kissy Sullivan,20,LinkedIn,Fully Meets,4.07,4,0,2019-02-28,0,13
307,Ybarra Catherine,10301,0,0,0,5,5,1,0,48513,...,Brannon Miller,12,Google Search,PIP,3.20,2,0,2015-09-02,5,4
308,Zamora Jennifer,10010,0,0,0,1,3,4,0,220450,...,Janet King,2,Employee Referral,Exceeds,4.60,5,6,2019-02-21,0,16
309,Zhou Julia,10043,0,0,0,1,3,3,0,89292,...,Simon Roup,4,Employee Referral,Fully Meets,5.00,3,5,2019-02-01,0,11
310,Zima Colleen,10271,0,4,0,1,5,3,0,45046,...,David Stanley,14,LinkedIn,Fully Meets,4.50,5,0,2019-01-30,0,2